@echo off
echo Cai dat Python va Pillow...
powershell -Command "Start-Process powershell -ArgumentList '-ExecutionPolicy Bypass -File \"%~dp0install_python.ps1\"' -Verb RunAs"
echo Khoi dong lai ung dung Laravel sau khi cai dat xong...
